"""★**集落の絵**（`docs/07-art-spec.md` §7.7）。32x32 で描いて 64x64 に 2 倍。

★**絵をコードに置く理由**: 手描きの .aseprite と違い、
ここは「文明ごとに色を替える」ための**下地**である。
どの画素がマゼンタ（色替えの対象）かが**読んで分かる**必要があるので、
ASCII で持って生成する。人が描いた .aseprite を後から差し替えてよい。

  M 主部（#FF00FF → 文明の色）  S 影（#AA00AA）  H ハイライト（#FF88FF）
  o 輪郭   w 窓・灯り   g 植生   k 煙・土   b 石   f 炎   . 透過

  python3 scripts/art/towns.py
"""
import zlib, struct, os

C = {
    "M": (255, 0, 255, 255),
    "S": (170, 0, 170, 255),
    "H": (255, 136, 255, 255),
    "o": (26, 22, 20, 255),
    "w": (232, 210, 140, 255),
    "g": (78, 132, 58, 255),
    "k": (96, 84, 68, 255),
    "b": (126, 118, 110, 255),
    "f": (255, 148, 62, 255),
    ".": (0, 0, 0, 0),
}

# ---------------------------------------------------------------- 集落
CAMP = """
................................
................................
................................
................................
................................
................................
................................
..............oo................
.............oHMo...............
.............oHMo...............
............oHMMSo..............
...........oHMMMSSo.............
..........oHMMMMSSSo............
.........oHMMMMMSSSSo...........
........oHMMMMMMSSSSSo..........
.......oMMMMMMMMSSSSSSo.........
......ooooooooooooooooooo.......
.................oo.....ff......
...............ooHMo....ff......
..............oHMMSSo..ffff.....
.............oHMMMSSSo.ffff.....
............oMMMMMSSSSofffff....
...........oooooooooooooooooo...
...........kkkkkkkkkkkkkkkkkk...
................................
................................
................................
................................
................................
................................
................................
................................
"""

# ---------------------------------------------------------------- 農村
VILLAGE = """
................................
................................
................................
................................
................................
..............oo................
.............oHMo...............
............oHMMSo..............
...........oHMMMSSo.............
..........oHMMMMSSSo............
.........oHMMMMMSSSSo...........
........oHMMMMMMSSSSSo..........
.......oooooooooooooooo.........
.......oMMMMMMMMMSSSSSo.........
.......oMMwwMMMMMSSSSSo.........
.......oMMwwMMMMMSSSSSo.........
.......oMMMMMMoooMSSSSo.........
.......oMMMMMMowwoSSSSo.........
.......oMMMMMMowwoSSSSo.........
.......ooooooooooooooooo........
................................
..gg..gg..gg..gg..gg..gg..gg....
..gg..gg..gg..gg..gg..gg..gg....
.kkkkkkkkkkkkkkkkkkkkkkkkkkkk...
................................
................................
................................
................................
................................
................................
................................
................................
"""

# ---------------------------------------------------------------- 城壁都市
WALLED = """
................................
................................
..............oo................
.............oHMo...............
............oHMMSo..............
...........oHMMMSSo.............
..........oHMMMMSSSo............
.........ooooooooooooo..........
.........oMMHMMMSSSSSo..........
.........oMMHMMMSSSSSo..........
.........oMMwwMMSSSSSo..........
.........oMMwwMMSSSSSo..........
.........oMMHMMMSSSSSo..........
...ooo...oMMHMMMSSSSSo...ooo....
...oMo...oMMHMMMSSSSSo...oSo....
..ooooooooooooooooooooooooooo...
..oMoMoMoMHMMMMMMMMSSSSoSoSo....
..oMMMMMMMHMMMMMMMMSSSSSSSSo....
..oMMMMMMMHMMoooooMSSSSSSSSo....
..oMMMMMMMHMMowwwoMSSSSSSSSo....
..oMMMMMMMHMMowwwoMSSSSSSSSo....
..ooooooooooooooooooooooooooo...
..kkkkkkkkkkkkkkkkkkkkkkkkkkk...
................................
................................
................................
................................
................................
................................
................................
................................
................................
"""

# ---------------------------------------------------------------- 石造都市
STONE = """
................................
..............b.................
.............bbb................
............bbbbb...............
...........obbbbbo..............
..........obbbbbbbo.............
...b......oHMMMMMSSo......b.....
..bbb.....oHMMMMMSSo.....bbb....
.obbbo....oHMMMMMSSo....obbbo...
.oHMSo....oHMMMMMSSo....oHMSo...
.oHMSo....oHMwwwMSSo....oHMSo...
.oHMSo....oHMwwwMSSo....oHMSo...
.oHMSo....oHMwwwMSSo....oHMSo...
.oHMSo....oHMMMMMSSo....oHMSo...
.oHMSo...ooooooooooo....oHMSo...
.oHMSo...oHMMMMMMSSo....oHMSo...
.oHwSo...oHMMMMMMSSo....oHwSo...
.oHMSo...oHMoowoowoo....oHMSo...
oooooo...oHMowwowwSo....oooooo..
oHMMMSo..oHMowwowwSo...oHMMMSo..
oHMoMSo..oHMoowoowoo...oHMoMSo..
oHMwMSo.ooooooooooooo..oHMwMSo..
oHMoMSo.oHMMMMMMMSSSo..oHMoMSo..
ooooooooooooooooooooooooooooooo.
oMMMMMMMMMMoowwooMSSSSSSSSSSSSo.
oMMMMMMMMMMowwwwoMSSSSSSSSSSSSo.
ooooooooooooowwooooooooooooooooo
.kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
................................
................................
................................
................................
"""

# ---------------------------------------------------------------- 産業都市
INDUSTRIAL = """
................................
.....kk.........................
....kkkk........kk..............
...kkkkkk......kkkk.............
....kkkk......kkkkkk............
.....kk........kkkk.............
....oooo........kk..............
....oSSo.......oooo.............
....oSSo.......oSSo.............
....oMSo.......oMSo.............
....oMSo.......oMSo.............
....oMSo.......oMSo.............
....oMSo.......oMSo.............
..oooooooo...oooooooo...........
..oHMMMSSo...oHMMMSSo..ooooo....
..oHMwMSSo...oHMwMSSo..oHMSo....
..oHMMMSSo...oHMMMSSo..oHwSo....
..oHMwMSSo...oHMwMSSo..oHMSo....
.oooooooooooooooooooooooooooo...
.oHMMMMMMMMMMMMMSSSSSSSSSSSSo...
.oHMwwMMwwMMwwMMSSwwSSwwSSSSo...
.oHMwwMMwwMMwwMMSSwwSSwwSSSSo...
.oHMMMMMMMMMMMMMSSSSSSSSSSSSo...
.oHMwwMMwwMMwwMMSSwwSSwwSSSSo...
.oHMwwMMwwMMwwMMSSwwSSwwSSSSo...
.oooooooooooooooooooooooooooo...
..kkkkkkkkkkkkkkkkkkkkkkkkkkk...
................................
................................
................................
................................
................................
"""

# ---------------------------------------------------------------- 近代都市
MODERN = """
................................
...........oooo.................
...........oHSo.................
...........oHSo.................
....oooo...oHSo.................
....oHSo...oHSo....oooooo.......
....oHSo...oHSo....oHMMSo.......
....oHSo...oHSo....oHMMSo.......
..oooooooooooooo...oHMMSo.......
..oHwwMSwwMSwwSo...oHMMSo.......
..oHMMMSMMMSMMSo..oooooooo......
..oHwwMSwwMSwwSo..oHwwMSSo......
..oHMMMSMMMSMMSo..oHMMMSSo......
..oHwwMSwwMSwwSo..oHwwMSSo......
..oHMMMSMMMSMMSo..oHMMMSSo......
.oooooooooooooooooooooooooo.....
.oHwwMMSwwMMSwwMMSSwwMMSSSo.....
.oHMMMMSMMMMSMMMMSSMMMMSSSo.....
.oHwwMMSwwMMSwwMMSSwwMMSSSo.....
.oHMMMMSMMMMSMMMMSSMMMMSSSo.....
.oHwwMMSwwMMSwwMMSSwwMMSSSo.....
.oHMMMMSMMMMSMMMMSSMMMMSSSo.....
.oHwwMMSwwMMSwwMMSSwwMMSSSo.....
.oooooooooooooooooooooooooooo...
.owwoooowwoooowwoooowwoooowwo...
.oooooooooooooooooooooooooooo...
..kkkkkkkkkkkkkkkkkkkkkkkkkkk...
................................
................................
................................
................................
................................
"""

ART = {
    "camp": CAMP, "village": VILLAGE, "walled": WALLED,
    "stone": STONE, "industrial": INDUSTRIAL, "modern": MODERN,
}


def png(path, w, h, rgba):
    """PIL に頼らず PNG を書く（依存を増やさない）"""
    raw = b"".join(b"\x00" + bytes(rgba[y * w * 4:(y + 1) * w * 4]) for y in range(h))
    def chunk(tag, data):
        c = tag + data
        return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c))
    out = b"\x89PNG\r\n\x1a\n"
    out += chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0))
    out += chunk(b"IDAT", zlib.compress(raw, 9))
    out += chunk(b"IEND", b"")
    open(path, "wb").write(out)


def build(name, art, scale=2):
    rows = [r for r in art.strip("\n").split("\n")]
    h0 = len(rows)
    w0 = max(len(r) for r in rows)
    assert w0 == 32 and h0 == 32, f"{name}: {w0}x{h0}（32x32 で描くこと）"
    w, h = w0 * scale, h0 * scale
    buf = bytearray(w * h * 4)
    for y, row in enumerate(rows):
        for x, ch in enumerate(row.ljust(w0, ".")):
            r, g, b, a = C.get(ch, C["."])
            for dy in range(scale):
                for dx in range(scale):
                    i = ((y * scale + dy) * w + (x * scale + dx)) * 4
                    buf[i:i + 4] = bytes((r, g, b, a))
    out = os.path.join("public", "icons", f"town-{name}.png")
    png(out, w, h, buf)
    return out


if __name__ == "__main__":
    for k, v in ART.items():
        print("書いた:", build(k, v))
